# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "  Home  "
    url: '#about'
    weight: 10
  - name: "  Publications  "
    url: 'https://www.brendeneum.com/publication/'
    weight: 20
  - name: "  Teaching  "
    url: 'https://www.brendeneum.com/teaching/'
    weight: 25
#  - name: "  Graduate Consulting  "
#    url: 'https://www.brendeneum.com/consulting/'
#    weight: 30
    # Link to a PDF of your resume/CV from the menu.
    # To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: "  CV  "
    url: uploads/cv.pdf
    weight: 40
  - name: "  Adventures  "
    url: 'https://www.brendeneum.com/adventures/'
    weight: 50
  - name: "  Late Night Bayes â˜¾  "
    url: 'https://www.brendeneum.com/LateNightBayes/'
    weight: 55
#    url: 'http://latenightbayes.com/index.html'
  - name: "  Contact  "
    url: '#contact'
    weight: 60